ottertune/ot-agent

driver/aws/rds.py, driver/driver_config_builder.py, tests/config_builder_test.py
Can see results with db 125 in nappelson@ottertune.com organization
=> Fix aurora mysql 5.6 issue

driver/collector/mysql_collector.py, driver/compute_server_client.py, tests/db_test_mysql.py, tests/mocks/mock_collector.py
Merge driver changes:
- DateTime serializable
- Filter MySQL schemas
=> DateTime serializable & Filter MySQL schemas

Dockerfile, driver/compute_server_client.py, driver/driver_config_builder.py, driver/main.py
Allow using env vars to override table level configs
Forgot to modify docker file to pass override env vars via cli
Tested locally
=> Allow overriding table level configs & bump version

driver/collector/pg_table_level_stats_sqls.py, driver/collector/postgres_collector.py, driver/compute_server_client.py
A comma makes the table list fail
Tested locally
=> Fix bug & bump version to 0.3.7

driver/collector/mysql_collector.py, driver/collector/pg_table_level_stats_sqls.py, driver/collector/postgres_collector.py, tests/db_test_postgres.py, tests/mysql_collector_test.py, tests/postgres_collector_test.py
Adding Index data collection for MySQL
=> OTT-2184: Implement Data Collection in Driver/Agent MySQL

.circleci/config.yml, driver/collector/pg_table_level_stats_sqls.py, driver/collector/postgres_collector.py, tests/postgres_collector_test.py
Adding data collection for Index Health (Postgres).
=> OTT-2184: Implement Data Collection in Driver/Agent Postgres

driver/config/driver_config.yaml
=> Add num_index_to_collect_stats

.circleci/config.yml
Making strings like 0.3.9-alpha valid release tag names.
=> Add testing release tag pattern

driver/compute_server_client.py
=> bump version to 0.3.10

README.md
Some reminder text about updating the new agent release fixture when releasing a new version of the agent.
=> [OTT-2348] update README -- reminder to update new Agent Release fixture

README.md
Add a FigJam code flow diagram to the README
As a result of work on https://github.com/ottertune/ot-agent/pull/67
N/A
=> Add code flow diagram to README.md

driver/compute_server_client.py, driver/pipeline.py, requirements.txt
=> Fix decimal serialization

driver/compute_server_client.py
=> Fix proxy auth header for query observation

driver/compute_server_client.py
=> Fix datetime serialization

driver/compute_server_client.py
=> Use a different timeout value for posting query observation

driver/compute_server_client.py, driver/config/cloudwatch_metrics/rds_aurora_postgresql-14.json
=> CloudWatch fixtures for aurora pg 14

.circleci/config.yml
=> Build nightly images

driver/compute_server_client.py
=> Change version string back to 0.3.16

driver/collector/collector_factory.py, driver/collector/postgres_collector.py, driver/config/driver_config.yaml, driver/driver_config_builder.py, tests/db_test_postgres.py, tests/postgres_collector_test.py
Adds support for multiple databases in postgres (this already exists for mysql)
https://ottertune.atlassian.net/jira/software/c/projects/OTT/boards/7?modal=detail&selectedIssue=OTT-2675&assignee=604f57a786b0dd00715335a3
Testing on local
=> OTT-2675 Multi db

driver/compute_server_client.py, driver/driver_config_builder.py, driver/main.py
- Bumps minor version to 0.4.0 for next release
- Fixes some lint changes in a recent open source contribution, linter must not be running properly on non-OT pr's?
=> Bump minor version to 0.4.0 + lint fixes

driver/driver_config_builder.py, tests/db_test_postgres.py
Remove unused parameter for multi-db support
Multi-DB support
n/a
=> Remove unused parameter - pg_db_list

driver/compute_server_client.py, driver/config/cloudwatch_metrics/rds_postgres-15.json, requirements-dev.txt
=> Add postgres 15 fixtures

tests/postgres_collector_test.py
=> long running query testing fixes

driver/collector/postgres_collector.py, requirements-dev.txt, requirements.txt, tests/collector_factory_test.py, tests/mysql_collector_test.py, tests/postgres_collector_test.py
Update few packages for security issue.
=> Security patch

Dockerfile, README.md, driver/compute_server_client.py, driver/main.py, tests/pipeline_test.py
=> Fix long running query parameter

driver/compute_server_client.py
Updates version number to a soon-to-be released tag.
=> Update version number to soon-to-be released release

driver/driver_config_builder.py, driver/main.py, driver/pipeline.py, driver/s3_client.py, tests/s3_client_test.py
Test the idea of S3 support, will add test if it is Ok.
=> Support sending observation data to S3

Dockerfile
Update dockerfile for S3 support
=> Update dockerfile for s3 support

driver/pipeline.py, driver/s3_client.py, tests/s3_client_test.py
=> Add headers for compute service requests to observation data

Dockerfile, driver/agent_health_heartbeat.py, driver/aws/rds.py, driver/aws/wrapper.py, driver/collector/collector_factory.py, driver/collector/pg_table_level_stats_sqls.py, driver/collector/postgres_collector.py, driver/database.py, driver/driver_config.py, driver/driver_config_builder.py, driver/main.py, driver/pipeline.py, driver/s3_client.py, tests/agent_health_test.py, tests/collector_factory_test.py, tests/compute_server_client_test.py, tests/config_builder_test.py, tests/db_test_mysql.py, tests/db_test_postgres.py, tests/mocks/mock_collector.py, tests/mysql_collector_test.py, tests/postgres_collector_test.py, tests/s3_client_test.py, tests/useful_literals.py
To support sending observation data to customer's bucket
Improvement for existing S3 support, which sends data to OtterTune S3 only
Updated unit tests
=> Support customer s3 bucket

agent_version.py
tag 0.5.2 is already created before this change. So use 0.5.3
=> Update agent version

agent_version.py, driver/collector/postgres_collector.py
=> 0.5.2 Collect pg_stat_statement errors

agent_version.py
=> Update version to 0.5.6

requirements.txt
=> Update pip version

README.md
Update instruction for installing agent via Helm Chart
=> Update instruction for Helm Chart

agent_version.py, driver/config/cloudwatch_metrics/rds_postgres-16.json
=> Support pg16

agent_version.py, driver/config/cloudwatch_metrics/rds_aurora_postgresql-16.json
=> Support aurora pg16
